### ISSUE TITLE
Small strain elasto-plastic model

### ISSUE THREAD

**Issue by RyotaHashimoto** [geomechanics/mpm#20]
This issue aims to implement the consistent tangent matrix of the small strain Mohr-Coulomb model for the implicit solver.

**Comment by bodhinandach** [comment]
@yliang-sn We should use this for XMPM too. @RyotaHashimoto will develop the format, and then let's try to incorporate this to XMPM

**Comment by yliang-sn** [comment]
> @yliang-sn We should use this for XMPM too. @RyotaHashimoto will develop the format, and then let's try to incorporate this to XMPM

It sounds good. I will incorporate it to the XMPM.

**Comment by bodhinandach** [comment]
We have Mohr-Coulomb, Modified Cam Clay and NorSand so far. @yliang-sn We need to implement `D_epp` too right other than `D_ep` for your purpose? Let's discuss.

**Comment by bodhinandach** [comment]
Just to keep it noted, as I said in the meeting, @yliang-sn if you look PR #21, the way you should call the function will be:

`material_->compute_elasto_plastic_tensor(stress, dstrain, ptr, state_vars, false);`

to obtain the `D_epp` for acoustic tensor evaluation of strong discontinuity.
