### ISSUE TITLE
Track code changes with github-based documentation

### ISSUE THREAD

**Issue by jgiven100** [geomechanics/mpm#22]
## Improvement Idea

Use **either**:

1. input markdown file; or
2. the github wiki feature 
 
to improve the documentation of features added to geomechanics repo. 

## Untracked Changes

Features already merged into geomechanics (without documentation) mentioned in Dec. 2 dev meeting:

* Implicit MPM
* 2 phase

**Comment by bodhinandach** [comment]
I would say that we can just move all the details to WIKI, e.g. installation, input file, author lists, etc.? Do you think that it is neater?

**Comment by jgiven100** [comment]
I think so!

**Comment by jgiven100** [comment]
Linked documentation PR has been closed since we are using the WIKI.

Lets leave this issue open to remind us to update the WIKI for features already merged -> 2 phase, implicit.

**Comment by bodhinandach** [comment]
So related to the discussions on Monday, here are some todo checklists to improve on documentation side:

- [ ] WIKI is set: Thanks to @jgiven100 
- [ ] Installation guidelines: @bodhinandach needs to add PETSc installation procedures, @LDTalbot check if installation is alright.
- [ ] main readme: remove after every information is moved to WIKI
- [ ] material models: @jgiven100 @bodhinandach @RyotaHashimoto 
- [ ] another benchmark repo: @jgiven100 @bodhinandach @RyotaHashimoto @yliang-sn 

Let me know if I miss anything.

**Comment by jgiven100** [comment]
Would we want to make seperate "input file" wiki pages for 1 phase, 2 phase, and implicit? @bodhinandach 

It would be a lot of repeated content, but from what I remember, it can get a bit difficult to be clear about the differences in input files for 1 and 2 phase if its a shared section the same section.

**Comment by jgiven100** [comment]
@bodhinandach Just checked material inputs and everything looked ok to me. For MCC I added a note for `OCR` vs. `e_0` vs. `n` being acceptable. For BNS I added a note for `e_0` vs. `n` being acceptable. 

I remember someone mentioning that the docs needed the elastc parameters (Young's modulus, Shear modulus, etc.) updated. But I didn't see any discrepancies. Did someone else already take care of this?

**Comment by jgiven100** [comment]
@bodhinandach I was expected to see both polar and cartesian stresses here. Or was that only added to cutmesh? 
https://github.com/geomechanics/mpm/blob/master/include/solvers/mpm_base.tcc#L24-L36

**Comment by jgiven100** [comment]
@LDTalbot @bodhinandach all VTK options added to Docs

**Comment by bodhinandach** [comment]
@RyotaHashimoto @jgiven100 @yliang-sn I think in the next meeting we should discuss what testing we can upload to our benchmark repo.

**Comment by jgiven100** [comment]
Sounds good. 

I also think we can close this general issue, then open specific issues for the outstanding items? From what I see, its just 2 phase docs and implicit docs

**Comment by bodhinandach** [comment]
I will finish them by this weekend and then let's close this one

**Comment by bodhinandach** [comment]
Are we good with this issue now? Sorry for the long delay. I will update the documentations periodically from now on.
