### ISSUE TITLE
Hencky strain implementation

### ISSUE THREAD

**Issue by bodhinandach** [geomechanics/mpm#25]
@RyotaHashimoto , let's start discussing the finite strain implementation here. I am thinking that other than providing an option for users to choose small/finite strain, we need to do the following:
1. Material model with finite strain
2. Volume update with finite strain
3. Geometric stiffness matrix (should be added to the default tangent matrix)
4. Add treatment of volumetric locking (HKU team's work on smoothing the Deformation Gradient)
5. Code validation

Any further thoughts?

**Comment by RyotaHashimoto** [comment]
@bodhinandach I think that your plan is good for our first step.
