### ISSUE TITLE
Particle is going out of bound after PR #37

### ISSUE THREAD

**Issue by bodhinandach** [geomechanics/mpm#42]
**Describe the bug**
There is a new bug after PR #37 is merged. I am so sorry for not checking this before.

Here is the problem: the new update of displacement uses the old particle velocity with the factor of a half. This is not good since the boundary condition might not be imposed appropriately nearby the boundary.

I am currently finding a way to mitigate this but at the same time correct the error. In the meantime, I would propose that we revert PR #37 since it is breaking.

Simulation results before and after PR #37.
![image](https://user-images.githubusercontent.com/37140224/156452882-ea92e432-17d2-403a-b6c0-3c33966f8b8e.png)
![image](https://user-images.githubusercontent.com/37140224/156452902-9a485324-9b1d-4546-a911-6a3eee02cfaa.png)

**Comment by jgiven100** [comment]
lets revert
