### ISSUE TITLE
Stress Inputs

### ISSUE THREAD

**Issue by jgiven100** [geomechanics/mpm#54]
**Describe the bug**
[geomechanics wiki](https://github.com/geomechanics/mpm/wiki/Explicit-Single-Phase-MPM) doesn't have the details for using `"isotropic"` flag with particles stresses. Right now it only shows:
```
        "particles_stresses": {
          "type": "file",
          "file": "particles-stresses.txt"
        },
```

I'm having trouble getting the `"isotropic"` flag to work on my own. 

If correct syntax is provided here, I'll update the wiki.

**Comment by bodhinandach** [comment]
I updated the wiki. Sorry for this.

**Comment by jgiven100** [comment]
@bodhinandach I wasn't using square brackets for `"values"` :facepalm: thanks for updating!
