### ISSUE TITLE
SIGSTKSZ is not an integral constant with libc6 2.34

### ISSUE THREAD

**Issue by migmolper** [geomechanics/mpm#61]
**Describe the bug**
Updated versions of Ubuntu (21.10 and superiors) installed  libc6 (glibc) 2.34.   SIGSTKSZ  [is now no longer constant](https://sourceware.org/pipermail/libc-alpha/2021-August/129718.html), and can’t be used directly to define array sizes. According to documentation:

"The constant SIGSTKSZ is defined to be large enough to cover the usual size requirements for an alternate signal stack".

See similar PR's in other people's codes:
- [doctest git](https://github.com/doctest/doctest/issues/473)
- [json git](https://github.com/nlohmann/json/issues/2686)

And this is a proposed fix to the bug:
- [json git](https://github.com/nlohmann/json/pull/2687)

Affected file in the code:
- [mpm/external/catch.hpp](https://github.com/geomechanics/mpm/blob/master/external/catch.hpp)

Any thoughts @bodhinandach ?

**To Reproduce**
These are my machine specifications: "Ubuntu 22.04 LTS" and  "gcc 11.2.0"

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/24325772/171141098-aee6993d-2bf9-44c0-bd92-c18de8f12fc2.png)

**Comment by bodhinandach** [comment]
Is this related to the testing? Let me have a look at it this week. Let's discuss this on Friday.

**Comment by bodhinandach** [comment]
@migmolper How are we dealing with this one?

**Comment by migmolper** [comment]
We are using this:

/*******************/

#include <cstdlib>
#if defined(_SC_SIGSTKSZ_SOURCE) || defined(_GNU_SOURCE)
// on glibc > 2.33 this is no longer constant, see
// https://sourceware.org/git/?p=glibc.git;a=blob;f=NEWS;h=85e84fe53699fe9e392edffa993612ce08b2954a;hb=HEAD
static constexpr std::size_t sigStackSize = 32768;
#else
static constexpr std::size_t sigStackSize =
    32768 >= SIGSTKSZ ? 32768 : SIGSTKSZ;
#endif

/*******************/

And then substitute SIGSTKSZ by sigStackSize

**Comment by bodhinandach** [comment]
This runs the test ok in the newer version of Linux?
