### ISSUE TITLE
Particles go out of bound

### ISSUE THREAD

**Issue by QuackFrog** [geomechanics/mpm#80]
**Describe the bug**
I have used the `MPMExplicit2D` solver for a  2D slope failure problem and `MPMExplicit3D` solver for a water dam break problem. Unfortunately, I encountered material points crossing the fixed boundaries (velocity set to 0 in specified directions) in both cases. I double-checked the setting of the boundary conditions and did not find a problem. 

I modified the source code of the program to output the coordinates of these out-of-bounds particles. And I found that the coordinates of these particles are like (-1.75539e-18, 0.999947, 3.17375e-07) when I have a fixed bound in x=0 and the particles should have been located within 0<x<0.2. A screenshot of my console is shown.

<img width="787" alt="Snipaste_2022-11-25_22-37-49" src="https://user-images.githubusercontent.com/64186092/204012214-14c4ccca-e3e1-4bb2-bb80-f5817f93111d.png">

`ED2Q4` and `ED3Q8` elements are used for 2D and 3D problems, respectively. Both `usf` and `musl` update schemes are tested and both take a time step dt=1.0E-4. Only velocity constraints are set.

**To Reproduce**
1. The code is compiled on Ubuntu 20.04 on WSL2 without mpi. The compilation results passed all tests.
2. The code runs on Ubuntu 20.04 on WSL2.
3. Take the water dam break problem as an example. As shown in the following figure, I meshed a box of 0.2x1.0x1.0 and generated a set of particles forming a box of 0.2x0.2x0.4. All six faces of the meshed box are set zero-velocity constraints in the normal direction. 

<img width="954" alt="Snipaste_2022-11-25_22-47-44" src="https://user-images.githubusercontent.com/64186092/204010698-568a8b19-bfbd-4f4c-9e5b-ace44f0b22dd.png">

**Expected behavior**
Figure out what causes the bug and fix it.

**Runtime environment (please complete the following information):**
 - OS/Docker image: Ubuntu 20.04 on WSL2
 - Branch: master

**Additional context**
None

**Comment by bodhinandach** [comment]
Hi @QuackFrog, thanks for the message. Unfortunately, our group does not provide user support through this repository. Please go to https://github.com/cb-geo/mpm for user help. Thanks!
